version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: portal
      RABBITMQ_DEFAULT_PASS: none
    ports:
      - "5672:5672" # RabbitMQ
      - "15672:15672" # Management UI
    volumes:
      - ./file_storage/rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:latest
    ports:
      - "6379:6379" # Redis
    volumes:
      - ./file_storage/redis_data:/data
